import { PresentationProject, SlideData, PresentationConfig, UploadedDocument } from '@/types/presentation';

export const DEFAULT_CONFIG: PresentationConfig = {
  purpose: 'project_viva',
  audience: 'professor',
  duration: '10m',
  slideCount: '10',
  style: 'modern',
  colorTheme: 'classic_blue',
  density: 'balanced',
  visualIntensity: 'balanced',
};

export const SAMPLE_DOCUMENT: UploadedDocument = {
  id: 'doc-attendance-viva-2025',
  name: 'Smart_Attendance_System_Final_Report_v2.4.pdf',
  size: 3420000, // 3.4 MB
  type: 'pdf',
  pages: 42,
  uploadedAt: '2026-09-02T10:30:00Z',
};

export const MOCK_SLIDES: SlideData[] = [
  {
    id: 1,
    slideNumber: 1,
    title: 'Smart Attendance System using Deep Facial Recognition & Edge Computing',
    subtitle: 'Automated, Contactless Classroom Monitoring via Jetson Nano & 128-D FaceNet Embeddings',
    visualType: 'title',
    category: 'Title & Overview',
    durationSeconds: 60,
    speakerNotes: 'Good morning respected external examiners and professors. Today our team presents our Final Year Capstone Project: an autonomous, contactless smart attendance system powered by deep learning at the edge.',
    templateId: "tpl-mock",
    templateFamily: "modern",
    layoutStyle: "split",
    content: {
      authors: ['Engineering Lead (AI/ML)', 'Systems Architect', 'Security Engineer'],
      guide: 'Dr. S. Ranganathan, Professor & Head, Dept. of Computer Science & Engineering',
      institution: 'National Institute of Technology • Final Year B.Tech Viva Defense',
      academicYear: 'Academic Year 2025 - 2026',
      badge: 'Project Viva Defense • Phase II',
      tags: ['Edge AI', 'Computer Vision', 'PyTorch', 'NVIDIA Jetson', 'FastAPI'],
    },
  },
  {
    id: 2,
    slideNumber: 2,
    title: 'Problem Statement & Existing Bottlenecks',
    subtitle: 'Why traditional biometric systems fail in real-world educational institutions',
    visualType: 'problem_comparison',
    category: 'Problem Analysis',
    durationSeconds: 75,
    speakerNotes: 'In academic environments with 60 to 120 students per lecture hall, traditional methods introduce immense friction. Manual roll calls consume up to 15% of instructional time, while fingerprint scanners suffer from biological hygiene concerns and physical queue congestion.',
    templateId: "tpl-mock",
    templateFamily: "modern",
    layoutStyle: "split",
    content: {
      metrics: [
        { label: 'Time Wasted / Hour', value: '12-15 min', sub: 'Lost lecture duration on manual roll calls' },
        { label: 'Proxy Rate', value: '18.4%', sub: 'Undetected surrogate attendance in large classrooms' },
        { label: 'Sensor Throughput', value: '3.2 sec/student', sub: 'Physical queue delay on optical fingerprint scanners' },
      ],
      comparison: [
        {
          aspect: 'Manual Roll Call',
          flaw: 'High instructional time overhead; susceptible to human proxies; manual record digitization needed.',
          severity: 'High Overhead',
        },
        {
          aspect: 'Fingerprint Biometrics',
          flaw: 'Physical contact required; hardware sensor degradation from oil/dust; severe physical bottleneck at door.',
          severity: 'Bottleneck',
        },
        {
          aspect: 'RFID Card Swiping',
          flaw: 'Extreme proxy vulnerability (passing cards to peers); card replacement and re-issuance logistics.',
          severity: 'Zero Security',
        },
      ],
    },
  },
  {
    id: 3,
    slideNumber: 3,
    title: 'Proposed Solution: Zero-Touch Edge Attendance',
    subtitle: 'An intelligent multi-stage computer vision pipeline operating locally on embedded edge hardware',
    visualType: 'solution_pillars',
    category: 'Methodology',
    durationSeconds: 90,
    speakerNotes: 'Our solution addresses every single bottleneck. Instead of requiring active student interaction, ambient high-resolution cameras capture lecture hall frames, detect multiple faces in parallel, and match embeddings against an on-device local database in under 150 milliseconds.',
    templateId: "tpl-mock",
    templateFamily: "modern",
    layoutStyle: "split",
    content: {
      pillars: [
        {
          number: '01',
          title: 'Ambient Multi-Face Capture',
          desc: 'High-resolution wide-angle RTSP stream capturing the classroom simultaneously without requiring students to pause.',
          tag: 'Real-Time Acquisition',
        },
        {
          number: '02',
          title: 'Local Edge Processing',
          desc: '100% on-premise execution on NVIDIA Jetson Nano. Zero latency overhead, no bandwidth bottleneck, and strict biometric data privacy.',
          tag: 'Edge AI Inference',
        },
        {
          number: '03',
          title: 'Cosine Distance Match & Verification',
          desc: '128-dimensional triplet loss vectors compared with a calibrated 0.68 threshold to ensure zero false positives.',
          tag: '99.4% Accuracy',
        },
      ],
    },
  },
  {
    id: 4,
    slideNumber: 4,
    title: 'System Architecture & Data Flow',
    subtitle: 'End-to-end hardware-to-cloud decoupled microservice architecture',
    visualType: 'system_architecture',
    category: 'Architecture',
    durationSeconds: 120,
    speakerNotes: 'Here is our end-to-end architecture diagram. As professors often ask about data security and latency: notice that raw video feeds never leave the local Jetson module. Only verified timestamped attendance records are encrypted and dispatched to the institutional dashboard.',
    templateId: "tpl-mock",
    templateFamily: "modern",
    layoutStyle: "split",
    content: {
      layers: [
        {
          name: 'Input Layer',
          node: 'Sony IMX477 12MP Sensor',
          details: '4K @ 30fps RTSP feed • Wide FoV 120° coverage of lecture benches',
          type: 'Hardware Sensor',
        },
        {
          name: 'Edge Inference Node',
          node: 'NVIDIA Jetson Nano 4GB',
          details: '128-core Maxwell GPU • TensorRT FP16 quantization • 472 GFLOPS',
          type: 'Edge Compute',
        },
        {
          name: 'Deep Learning Pipeline',
          node: 'MTCNN + FaceNet Backbone',
          details: 'Bounding box alignment -> 128-D Euclidean Vector Extraction',
          type: 'Neural Network',
        },
        {
          name: 'Storage & Vector Match',
          node: 'SQLite + FAISS Vector Index',
          details: 'Sub-millisecond L2 similarity search over 500 enrolled student profiles',
          type: 'Local Database',
        },
        {
          name: 'Faculty & Cloud Dashboard',
          node: 'FastAPI + Next.js Portal',
          details: 'TLS 1.3 encrypted sync • Real-time absent notification via SMS/Email',
          type: 'Cloud Interface',
        },
      ],
    },
  },
  {
    id: 5,
    slideNumber: 5,
    title: 'Inference Pipeline: Frame to Attendance Log',
    subtitle: 'Sub-200ms processing loop optimized with TensorRT INT8/FP16 acceleration',
    visualType: 'workflow_pipeline',
    category: 'Technical Workflow',
    durationSeconds: 100,
    speakerNotes: 'Examining the inner processing pipeline: every 3 seconds, a high-resolution frame is sampled. MTCNN locates all human faces, affine transforms calibrate eye alignment, FaceNet generates the unit vector, and an anti-spoofing blink test rejects screen replays.',
    templateId: "tpl-mock",
    templateFamily: "modern",
    layoutStyle: "split",
    content: {
      steps: [
        {
          step: '1',
          name: 'Frame Sampling',
          tech: 'OpenCV CUDA VideoCapture',
          time: '12 ms',
          desc: 'Downsamples 1080p frame buffer while preserving facial pixel density',
        },
        {
          step: '2',
          name: 'Face Localization',
          tech: 'MTCNN / RetinaFace',
          time: '38 ms',
          desc: 'Multi-scale pyramid identifies bounding boxes & 5 facial landmarks',
        },
        {
          step: '3',
          name: 'Affine Alignment',
          tech: 'Similarity Transformation',
          time: '8 ms',
          desc: 'Normalizes roll, pitch, and yaw angles relative to eye centers',
        },
        {
          step: '4',
          name: 'Feature Extraction',
          tech: 'FaceNet Triplet Loss',
          time: '64 ms',
          desc: 'Quantized TensorRT engine outputs normalized 128-d vector embedding',
        },
        {
          step: '5',
          name: 'Anti-Spoofing & Match',
          tech: 'LBP + Cosine Similarity',
          time: '20 ms',
          desc: 'Detects screen glare/printed photos; logs attendance if cosine >= 0.72',
        },
      ],
      totalLatency: '142 ms total pipeline latency',
    },
  },
  {
    id: 6,
    slideNumber: 6,
    title: 'Experimental Results & Benchmark Evaluation',
    subtitle: 'Tested across 240 classroom sessions under varying illumination and occlusion conditions',
    visualType: 'results_charts',
    category: 'Empirical Results',
    durationSeconds: 110,
    speakerNotes: 'During our empirical testing across three academic departments over 4 weeks, our system recorded an overall recognition accuracy of 99.4% with optimal lighting, and sustained 94.2% even under severe 45-degree angled lighting and surgical mask wear.',
    templateId: "tpl-mock",
    templateFamily: "modern",
    layoutStyle: "split",
    content: {
      benchmarks: [
        { label: 'Overall Accuracy', value: '99.4%', change: '+14.2% vs Haar Cascade baseline', status: 'optimal' },
        { label: 'Pipeline Latency', value: '142 ms', change: 'Real-time multi-face throughput', status: 'optimal' },
        { label: 'False Acceptance Rate', value: '0.008%', change: 'Strict threshold eliminates false marks', status: 'optimal' },
        { label: 'False Rejection Rate', value: '0.41%', change: 'Seamlessly recovered on next frame', status: 'optimal' },
      ],
      conditions: [
        { condition: 'Normal Daylight (500 lux)', accuracy: 99.8, facesDetected: '60/60' },
        { condition: 'Dim Lecture Hall (120 lux)', accuracy: 97.4, facesDetected: '58/60' },
        { condition: 'Partial Occlusion (Spectacles / Masks)', accuracy: 94.6, facesDetected: '56/60' },
        { condition: 'Extreme Angles (>40° Pan)', accuracy: 92.1, facesDetected: '55/60' },
      ],
    },
  },
  {
    id: 7,
    slideNumber: 7,
    title: 'Bill of Materials & Economic Feasibility',
    subtitle: 'Total system deployment cost amortized over 4 academic batches',
    visualType: 'hardware_table',
    category: 'Hardware & Budget',
    durationSeconds: 70,
    speakerNotes: 'Cost is a major evaluation parameter for college deployment. A single smart classroom setup costs under 18,500 rupees, which is one-fourth the cost of commercial RFID turnstiles and biometric access barriers.',
    templateId: "tpl-mock",
    templateFamily: "modern",
    layoutStyle: "split",
    content: {
      items: [
        { component: 'NVIDIA Jetson Nano Developer Kit (4GB)', spec: '128-core Maxwell GPU, Quad-core ARM A57', cost: '₹12,400' },
        { component: 'Sony IMX477 HQ Camera Module', spec: '12.3 Megapixel, 6mm Wide Angle Lens', cost: '₹3,800' },
        { component: 'SanDisk Extreme Pro 128GB MicroSD', spec: 'U3 / V30 High Endurance Read/Write', cost: '₹1,200' },
        { component: '5V 4A Barrel Jack Power Supply & Aluminum Case', spec: 'Heatsink + Noctua PWM Active Fan', cost: '₹1,100' },
      ],
      totalCost: '₹18,500 ($220 USD)',
      roiNotice: 'Single unit services 150+ students across multiple lecture shifts daily.',
    },
  },
  {
    id: 8,
    slideNumber: 8,
    title: 'Anticipated Viva Defense Questions & Answers',
    subtitle: 'AI-predicted cross-examination points prepared for the external examiner',
    visualType: 'viva_defense',
    category: 'Viva Defense Readiness',
    durationSeconds: 90,
    speakerNotes: 'Here we have anticipated the most probable technical scrutiny points from the examiner, including handling twin confusion, spoofing attacks, and lighting variance, along with mathematical justifications.',
    templateId: "tpl-mock",
    templateFamily: "modern",
    layoutStyle: "split",
    content: {
      qaList: [
        {
          q: 'How does your model prevent photo/video spoofing on a smartphone screen?',
          a: 'We implemented Local Binary Pattern (LBP) texture analysis and specular reflection detection. Phone screens exhibit distinctive moiré patterns and high spectral reflectivity that fail our liveness classifier before embedding calculation.',
          badge: 'Security & Anti-Spoofing',
        },
        {
          q: 'Why choose FaceNet 128-D embeddings over traditional LBPH or Eigenfaces?',
          a: 'Eigenfaces rely on pixel Euclidean variance, making them fragile to slight illumination or pose shifts. FaceNet utilizes deep Convolutional Triplet Loss, mapping facial features to an invariant hypersphere where intra-class distance is mathematically minimized.',
          badge: 'Algorithmic Justification',
        },
        {
          q: 'What happens if two students have high facial similarity (e.g. identical twins)?',
          a: 'When cosine distance falls in the ambiguous threshold zone [0.65, 0.70], our system flags secondary multimodal verification (RFID badge or roll number confirmation) rather than making a confident false match.',
          badge: 'Edge-Case Handling',
        },
      ],
    },
  },
  {
    id: 9,
    slideNumber: 9,
    title: 'Future Scope & Engineering Roadmap',
    subtitle: 'Phased evolution towards campus-wide ambient intelligence',
    visualType: 'roadmap',
    category: 'Future Scope',
    durationSeconds: 60,
    speakerNotes: 'In future phases, we aim to extend this beyond attendance into student attentiveness analytics and multi-camera mesh tracking across corridors.',
    templateId: "tpl-mock",
    templateFamily: "modern",
    layoutStyle: "split",
    content: {
      milestones: [
        {
          phase: 'Phase 1 (Q3 2026)',
          title: 'Campus ERP & LMS Integration',
          desc: 'Direct REST webhook sync into Moodle, Canvas, and university SAP portals.',
        },
        {
          phase: 'Phase 2 (Q4 2026)',
          title: 'Attention & Engagement Analytics',
          desc: 'Head pose estimation and gaze tracking to provide professors with anonymous aggregate student engagement heatmaps.',
        },
        {
          phase: 'Phase 3 (Q1 2027)',
          title: 'Multi-Camera Correlated Mesh',
          desc: 'Distributed Jetson Orin Nano nodes sharing edge embeddings to cover stadium-sized auditoriums.',
        },
      ],
    },
  },
  {
    id: 10,
    slideNumber: 10,
    title: 'Conclusion & Acknowledgements',
    subtitle: 'Autonomous, scalable, and privacy-preserving academic attendance',
    visualType: 'conclusion',
    category: 'Summary',
    durationSeconds: 45,
    speakerNotes: 'In conclusion, we have demonstrated a production-viable, privacy-first edge system that cuts 15 minutes of wasted time per lecture down to zero seconds. We sincerely thank our project guide Dr. Ranganathan and the department faculty for their continuous mentorship.',
    templateId: "tpl-mock",
    templateFamily: "modern",
    layoutStyle: "split",
    content: {
      takeaways: [
        'Eliminated 100% of proxy attendance and physical biometric queues in pilot testing.',
        'Sub-150ms inference latency sustained on sub-₹20,000 embedded edge hardware.',
        'Zero cloud video transmission ensures total compliance with biometric privacy regulations.',
      ],
      thankYou: 'Thank you for your time. We are now open for viva cross-examination and queries.',
    },
  },
];

export const MOCK_PROJECT: PresentationProject = {
  id: 'proj-attendance-viva-2026',
  title: 'Smart Attendance System using Deep Facial Recognition & Edge Computing',
  description: 'AI-generated presentation for Final Year Engineering Project Viva Defense with architectural blueprints, experimental metrics, and anticipated questions.',
  document: SAMPLE_DOCUMENT,
  config: DEFAULT_CONFIG,
  slides: MOCK_SLIDES,
  createdAt: '2026-09-02T10:30:00Z',
  updatedAt: '2026-09-02T10:35:00Z',
    template: { id: "tpl-mock", name: "Mock", family: "modern", layoutStyle: "split", fontMood: "clean_sans", palette: { primary: "#000", secondary: "#000", accent: "#000", background: "#fff", text: "#000", cardBg: "#fff", border: "#eee", isDark: false } }
};

export const RECENT_PRESENTATIONS: PresentationProject[] = [
  MOCK_PROJECT,
  {
    id: 'proj-autonomous-drone-2026',
    title: 'Autonomous Quadcopter Navigation in GPS-Denied Environments',
    description: 'Seminar presentation exploring visual-inertial SLAM on STM32 flight controllers.',
    document: {
      id: 'doc-drone-slam',
      name: 'Drone_Visual_SLAM_Seminar_Report.docx',
      size: 4800000,
      type: 'docx',
      pages: 35,
      uploadedAt: '2026-09-01T14:20:00Z',
    },
    config: {
      purpose: 'seminar',
      audience: 'students',
      duration: '15m',
      slideCount: '15',
      style: 'modern',
      colorTheme: 'midnight',
      density: 'balanced',
      visualIntensity: 'visual_rich',
    },
    slides: MOCK_SLIDES.slice(0, 6),
    createdAt: '2026-09-01T14:20:00Z',
    updatedAt: '2026-09-01T14:25:00Z',
    template: { id: "tpl-mock", name: "Mock", family: "modern", layoutStyle: "split", fontMood: "clean_sans", palette: { primary: "#000", secondary: "#000", accent: "#000", background: "#fff", text: "#000", cardBg: "#fff", border: "#eee", isDark: false } }
  },
  {
    id: 'proj-cloud-microservices-2026',
    title: 'Event-Driven Microservices with Kafka & Kubernetes: A Benchmarking Study',
    description: 'Research paper presentation analyzing p99 latency in high-throughput distributed systems.',
    document: {
      id: 'doc-kafka-k8s',
      name: 'IEEE_Event_Driven_Benchmarking_Draft.pdf',
      size: 2100000,
      type: 'pdf',
      pages: 18,
      uploadedAt: '2026-08-28T16:10:00Z',
    },
    config: {
      purpose: 'research',
      audience: 'professor',
      duration: '10m',
      slideCount: '10',
      style: 'minimal',
      colorTheme: 'classic_blue',
      density: 'concise',
      visualIntensity: 'balanced',
    },
    slides: MOCK_SLIDES.slice(0, 6),
    createdAt: '2026-08-28T16:10:00Z',
    updatedAt: '2026-08-28T16:18:00Z',
    template: { id: "tpl-mock", name: "Mock", family: "modern", layoutStyle: "split", fontMood: "clean_sans", palette: { primary: "#000", secondary: "#000", accent: "#000", background: "#fff", text: "#000", cardBg: "#fff", border: "#eee", isDark: false } }
  },
];
