import { PresentationTemplate } from '@/types/templates';

export const PRESENTATION_TEMPLATES: PresentationTemplate[] = [
  {
    id: "apple-minimal",
    name: "Apple Studio Minimal",
    family: "apple_minimal",
    category: "Minimal",
    description: "Cupertino-inspired airiness with massive typographic hierarchy, subtle card fills, and pristine white space.",
    bestFor: ["Product Keynotes", "Executive Summaries", "High-Impact Thesis Defense"],
    palette: {
      primary: "#1D1D1F",
      secondary: "#6E6E73",
      accent: "#0071E3",
      background: "#FFFFFF",
      text: "#1D1D1F",
      cardBg: "#F5F5F7",
      border: "#E5E5EA",
      isDark: false,
    },
    fontMood: "clean_sans",
    layoutStyle: "apple-minimal",
    layoutFamily: "minimal",
    slideComposition: "hero-focused",
    shapeLanguage: "rounded-xl",
    spacingSystem: "airy-generous",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    isFeatured: true,
    previewSnippet: {
      title: "Less, but significantly better.",
      subtitle: "Airy breathing room and razor-sharp typographic discipline",
      tag: "CUPERTINO CLEAN",
      statValue: "100%",
      statLabel: "Focus Ratio",
    },
  },
  {
    id: "apple-dark",
    name: "Apple Pro Titanium",
    family: "apple_minimal",
    category: "Minimal",
    description: "Deep titanium dark mode canvas with sleek contrasting typography and Apple blue focus highlights.",
    bestFor: ["Developer Keynotes", "AI System Architecture", "Hardware Demonstrations"],
    palette: {
      primary: "#F5F5F7",
      secondary: "#A1A1A6",
      accent: "#2997FF",
      background: "#000000",
      text: "#F5F5F7",
      cardBg: "#1D1D1F",
      border: "#333336",
      isDark: true,
    },
    fontMood: "clean_sans",
    layoutStyle: "apple-minimal",
    layoutFamily: "minimal",
    slideComposition: "hero-focused",
    shapeLanguage: "rounded-xl",
    spacingSystem: "airy-generous",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    isFeatured: true,
    previewSnippet: {
      title: "Pro Workflow Architecture",
      subtitle: "Pure obsidian background with titanium level contrast",
      tag: "TITANIUM PRO",
      statValue: "3.2x",
      statLabel: "Bandwidth",
    },
  },
  {
    id: "apple-silver",
    name: "Apple Air Silver",
    family: "apple_minimal",
    category: "Minimal",
    description: "Crisp anodized aluminum silver aesthetic with subtle dark graphite type and space-gray accents.",
    bestFor: ["Engineering Demos", "Product Architecture", "Executive Decks"],
    palette: {
      primary: "#1F2937",
      secondary: "#4B5563",
      accent: "#2563EB",
      background: "#F9FAFB",
      text: "#111827",
      cardBg: "#FFFFFF",
      border: "#E5E7EB",
      isDark: false,
    },
    fontMood: "clean_sans",
    layoutStyle: "apple-minimal",
    layoutFamily: "minimal",
    slideComposition: "hero-focused",
    shapeLanguage: "rounded-xl",
    spacingSystem: "airy-generous",
    titlePosition: "top-left",
    cardStyle: "minimal-flat",
    visualStyle: "clean",
    previewSnippet: {
      title: "Precision Anodized Canvas",
      subtitle: "Aluminum contrast engineered for readability",
      tag: "AIR SILVER",
      statValue: "99.8%",
      statLabel: "Clarity",
    },
  },
  {
    id: "swiss-red",
    name: "Zurich International Red",
    family: "swiss_editorial",
    category: "Modern",
    description: "Strict asymmetric Zurich grid discipline, bold red accent spine, and unapologetic Swiss typography.",
    bestFor: ["Research Defense", "Scientific Architecture", "Formal Capstone Presentations"],
    palette: {
      primary: "#0A0A0A",
      secondary: "#525252",
      accent: "#EF4444",
      background: "#FAFAFA",
      text: "#0A0A0A",
      cardBg: "#FFFFFF",
      border: "#E5E5E5",
      isDark: false,
    },
    fontMood: "bold_display",
    layoutStyle: "asymmetric-grid",
    layoutFamily: "swiss-grid",
    slideComposition: "asymmetric-split",
    shapeLanguage: "sharp-corners",
    spacingSystem: "asymmetric-gutters",
    titlePosition: "top-left",
    cardStyle: "outline-only",
    visualStyle: "editorial",
    isFeatured: true,
    previewSnippet: {
      title: "Asymmetric Grid Discipline",
      subtitle: "Left red accent spine with mathematical typographic alignment",
      tag: "ZURICH SPEC",
      statValue: "100%",
      statLabel: "Order",
    },
  },
  {
    id: "swiss-mono",
    name: "Helvetica Monochrome",
    family: "swiss_editorial",
    category: "Modern",
    description: "Pure black-and-white International Typographic Style with strict grid hierarchies and zero fluff.",
    bestFor: ["Mathematical Papers", "System Theory", "Academic Reviews"],
    palette: {
      primary: "#000000",
      secondary: "#404040",
      accent: "#171717",
      background: "#FFFFFF",
      text: "#000000",
      cardBg: "#F5F5F5",
      border: "#D4D4D4",
      isDark: false,
    },
    fontMood: "bold_display",
    layoutStyle: "asymmetric-grid",
    layoutFamily: "swiss-grid",
    slideComposition: "asymmetric-split",
    shapeLanguage: "sharp-corners",
    spacingSystem: "asymmetric-gutters",
    titlePosition: "top-left",
    cardStyle: "outline-only",
    visualStyle: "editorial",
    previewSnippet: {
      title: "International Typographic Style",
      subtitle: "Pure high-contrast black and white structural hierarchy",
      tag: "BASEL MONO",
      statValue: "0%",
      statLabel: "Noise",
    },
  },
  {
    id: "swiss-ochre",
    name: "Basel Typographic Ochre",
    family: "swiss_editorial",
    category: "Modern",
    description: "Classic Swiss design with deep warm ochre spine and clean charcoal typography.",
    bestFor: ["Architecture Reviews", "Industrial Design", "Academic Seminars"],
    palette: {
      primary: "#1C1917",
      secondary: "#57534E",
      accent: "#D97706",
      background: "#FAF7F2",
      text: "#1C1917",
      cardBg: "#FFFFFF",
      border: "#E7E5E4",
      isDark: false,
    },
    fontMood: "bold_display",
    layoutStyle: "asymmetric-grid",
    layoutFamily: "swiss-grid",
    slideComposition: "asymmetric-split",
    shapeLanguage: "sharp-corners",
    spacingSystem: "asymmetric-gutters",
    titlePosition: "top-left",
    cardStyle: "outline-only",
    visualStyle: "editorial",
    previewSnippet: {
      title: "Basel Typographic Ochre",
      subtitle: "Warm amber accents over structured grid layout",
      tag: "BASEL OCHRE",
      statValue: "48ms",
      statLabel: "Sync",
    },
  },
  {
    id: "linear-dark",
    name: "Linear Obsidian",
    family: "linear_dark",
    category: "Technology",
    description: "Modern developer SaaS aesthetic with purple ambient glow, obsidian card elevations, and technical telemetry.",
    bestFor: ["Engineering Seminars", "Distributed Systems", "Cloud DevOps Architecture"],
    palette: {
      primary: "#F8FAFC",
      secondary: "#94A3B8",
      accent: "#8B5CF6",
      background: "#090A0F",
      text: "#F8FAFC",
      cardBg: "#12141F",
      border: "#23273A",
      isDark: true,
    },
    fontMood: "technical",
    layoutStyle: "linear-dark",
    layoutFamily: "cyber",
    slideComposition: "deck-columns",
    shapeLanguage: "rounded-xl",
    spacingSystem: "compact-dense",
    titlePosition: "top-left",
    cardStyle: "elevated-dark-glow",
    visualStyle: "glow",
    isFeatured: true,
    previewSnippet: {
      title: "Real-Time Edge Telemetry",
      subtitle: "Obsidian card elevations with violet laser borders",
      tag: "ENGINEERING SPEC",
      statValue: "28ms",
      statLabel: "P99 Latency",
    },
  },
  {
    id: "linear-cyan",
    name: "Linear Cyanide",
    family: "linear_dark",
    category: "Technology",
    description: "High-contrast dark engineering canvas with electric cyan laser highlights and elevated card modules.",
    bestFor: ["Network Protocols", "Security Research", "Robotics Defense"],
    palette: {
      primary: "#F8FAFC",
      secondary: "#94A3B8",
      accent: "#06B6D4",
      background: "#080B11",
      text: "#F8FAFC",
      cardBg: "#0F1622",
      border: "#1E2A3B",
      isDark: true,
    },
    fontMood: "technical",
    layoutStyle: "linear-dark",
    layoutFamily: "cyber",
    slideComposition: "deck-columns",
    shapeLanguage: "rounded-xl",
    spacingSystem: "compact-dense",
    titlePosition: "top-left",
    cardStyle: "elevated-dark-glow",
    visualStyle: "glow",
    previewSnippet: {
      title: "Sub-millisecond Packet Flow",
      subtitle: "Electric cyan laser outlines on dark telemetry core",
      tag: "CYANIDE SPEC",
      statValue: "10Gbps",
      statLabel: "Throughput",
    },
  },
  {
    id: "linear-graphite",
    name: "Linear Graphite Carbon",
    family: "linear_dark",
    category: "Technology",
    description: "Stealth carbon fiber dark mode with emerald green status indicators and clean terminal telemetry.",
    bestFor: ["DevOps Pipelines", "SRE Architecture", "Microservices"],
    palette: {
      primary: "#FFFFFF",
      secondary: "#9CA3AF",
      accent: "#10B981",
      background: "#0F1115",
      text: "#F3F4F6",
      cardBg: "#181B22",
      border: "#282E3A",
      isDark: true,
    },
    fontMood: "technical",
    layoutStyle: "linear-dark",
    layoutFamily: "cyber",
    slideComposition: "deck-columns",
    shapeLanguage: "rounded-xl",
    spacingSystem: "compact-dense",
    titlePosition: "top-left",
    cardStyle: "elevated-dark-glow",
    visualStyle: "glow",
    previewSnippet: {
      title: "Autonomous Cluster Scaling",
      subtitle: "Graphite carbon texture with emerald green health telemetry",
      tag: "CARBON SPEC",
      statValue: "99.99%",
      statLabel: "Uptime SLA",
    },
  },
  {
    id: "bento-modern",
    name: "Bento Studio Light",
    family: "bento_grid",
    category: "Modern",
    description: "2026 Bento UI with modular asymmetric cards, prominent KPI hero blocks, and structured dashboard hierarchy.",
    bestFor: ["Product Launches", "Engineering Viva", "Portfolio Overviews"],
    palette: {
      primary: "#0F172A",
      secondary: "#64748B",
      accent: "#6366F1",
      background: "#F8FAFC",
      text: "#0F172A",
      cardBg: "#FFFFFF",
      border: "#E2E8F0",
      isDark: false,
    },
    fontMood: "clean_sans",
    layoutStyle: "bento-grid",
    layoutFamily: "bento",
    slideComposition: "modular-grid",
    shapeLanguage: "rounded-xl",
    spacingSystem: "balanced",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    isFeatured: true,
    previewSnippet: {
      title: "Modular Bento Architecture",
      subtitle: "Asymmetric multi-tile composition with integrated hero KPI",
      tag: "BENTO UI 2026",
      statValue: "4 Modules",
      statLabel: "Grid Hierarchy",
    },
  },
  {
    id: "bento-dark",
    name: "Bento Obsidian Matrix",
    family: "bento_grid",
    category: "Modern",
    description: "Deep obsidian bento grid tiles with subtle inner shadows, electric indigo borders, and high data density.",
    bestFor: ["Fintech Overviews", "Complex System Architecture", "AI Model Benchmarks"],
    palette: {
      primary: "#F8FAFC",
      secondary: "#94A3B8",
      accent: "#818CF8",
      background: "#0B0F17",
      text: "#F8FAFC",
      cardBg: "#131B2A",
      border: "#1E293B",
      isDark: true,
    },
    fontMood: "clean_sans",
    layoutStyle: "bento-grid",
    layoutFamily: "bento",
    slideComposition: "modular-grid",
    shapeLanguage: "rounded-xl",
    spacingSystem: "balanced",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    previewSnippet: {
      title: "Dark Mode Bento Matrix",
      subtitle: "Obsidian tiles with indigo telemetry highlights",
      tag: "OBSIDIAN BENTO",
      statValue: "100%",
      statLabel: "Modular",
    },
  },
  {
    id: "bento-pastel",
    name: "Bento Nordic Pastel",
    family: "bento_grid",
    category: "Creative",
    description: "Warm Scandinavian pastel tints across asymmetric bento blocks with gentle rounded contours.",
    bestFor: ["Design Sprints", "Product Reviews", "Creative Pitches"],
    palette: {
      primary: "#1E293B",
      secondary: "#64748B",
      accent: "#0D9488",
      background: "#F0FDF4",
      text: "#0F172A",
      cardBg: "#FFFFFF",
      border: "#DCFCE7",
      isDark: false,
    },
    fontMood: "clean_sans",
    layoutStyle: "bento-grid",
    layoutFamily: "bento",
    slideComposition: "modular-grid",
    shapeLanguage: "rounded-xl",
    spacingSystem: "balanced",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    previewSnippet: {
      title: "Nordic Pastel Bento",
      subtitle: "Soothing mint and sage modular containers",
      tag: "NORDIC BENTO",
      statValue: "4.9/5",
      statLabel: "Ergonomics",
    },
  },
  {
    id: "neo-brutalist-yellow",
    name: "Brutalist Cyber Yellow",
    family: "neo_brutalist",
    category: "Creative",
    description: "High-energy neo-brutalist design: heavy 3px black borders, solid offset drop shadows, and electric yellow cards.",
    bestFor: ["Hackathons", "Tech Pitches", "High-Impact Project Demonstrations"],
    palette: {
      primary: "#000000",
      secondary: "#262626",
      accent: "#FACC15",
      background: "#FEFCE8",
      text: "#000000",
      cardBg: "#FFFFFF",
      border: "#000000",
      isDark: false,
    },
    fontMood: "bold_display",
    layoutStyle: "neo-brutalist",
    layoutFamily: "brutalist",
    slideComposition: "deck-columns",
    shapeLanguage: "brutalist-solid",
    spacingSystem: "balanced",
    titlePosition: "top-left",
    cardStyle: "hard-border-shadow",
    visualStyle: "brutalist",
    isFeatured: true,
    previewSnippet: {
      title: "Unapologetic High Contrast",
      subtitle: "3px black borders with raw 5px offset solid shadows",
      tag: "POP BRUTALISM",
      statValue: "100%",
      statLabel: "Punch",
    },
  },
  {
    id: "neo-brutalist-pink",
    name: "Brutalist Acid Pink",
    family: "neo_brutalist",
    category: "Creative",
    description: "Ultra-vibrant hot magenta and black pop brutalism designed to shock audiences awake.",
    bestFor: ["Creative Direction", "Startup Pitch Competitions", "Student Demos"],
    palette: {
      primary: "#000000",
      secondary: "#262626",
      accent: "#EC4899",
      background: "#FDF2F8",
      text: "#000000",
      cardBg: "#FFFFFF",
      border: "#000000",
      isDark: false,
    },
    fontMood: "bold_display",
    layoutStyle: "neo-brutalist",
    layoutFamily: "brutalist",
    slideComposition: "deck-columns",
    shapeLanguage: "brutalist-solid",
    spacingSystem: "balanced",
    titlePosition: "top-left",
    cardStyle: "hard-border-shadow",
    visualStyle: "brutalist",
    previewSnippet: {
      title: "Hyper-Saturation Brutalism",
      subtitle: "Magenta impact with hard drop shadows and black boundaries",
      tag: "ACID POP",
      statValue: "0ms",
      statLabel: "Boredom",
    },
  },
  {
    id: "neo-brutalist-acid",
    name: "Brutalist Acid Lime",
    family: "neo_brutalist",
    category: "Creative",
    description: "High-voltage electric green with thick black structural lines and raw geometric blocks.",
    bestFor: ["Developer Keynotes", "Web3 / Crypto", "Creative Engineering"],
    palette: {
      primary: "#000000",
      secondary: "#1F2937",
      accent: "#84CC16",
      background: "#F7FEE7",
      text: "#000000",
      cardBg: "#FFFFFF",
      border: "#000000",
      isDark: false,
    },
    fontMood: "bold_display",
    layoutStyle: "neo-brutalist",
    layoutFamily: "brutalist",
    slideComposition: "deck-columns",
    shapeLanguage: "brutalist-solid",
    spacingSystem: "balanced",
    titlePosition: "top-left",
    cardStyle: "hard-border-shadow",
    visualStyle: "brutalist",
    previewSnippet: {
      title: "Acid Lime Pop",
      subtitle: "Raw geometric punch with hard 3px black outlines",
      tag: "LIME PUNCH",
      statValue: "100%",
      statLabel: "Voltage",
    },
  },
  {
    id: "cyber-neon",
    name: "Cyberpunk Neon Void",
    family: "future_tech",
    category: "Technology",
    description: "Blade Runner inspired obsidian void with electric violet-cyan neon laser rules and HUD telemetry.",
    bestFor: ["Autonomous Systems", "Neural Networks", "Robotics Thesis Defense"],
    palette: {
      primary: "#F8FAFC",
      secondary: "#94A3B8",
      accent: "#38BDF8",
      background: "#030712",
      text: "#F8FAFC",
      cardBg: "#0B1329",
      border: "#1E3A8A",
      isDark: true,
    },
    fontMood: "technical",
    layoutStyle: "cyber-tech",
    layoutFamily: "cyber",
    slideComposition: "deck-columns",
    shapeLanguage: "chamfered-hud",
    spacingSystem: "compact-dense",
    titlePosition: "top-left",
    cardStyle: "elevated-dark-glow",
    visualStyle: "glow",
    isFeatured: true,
    previewSnippet: {
      title: "Autonomous Neural Perception",
      subtitle: "Electric cyan laser brackets and telemetry HUD indicators",
      tag: "NEURAL CORE",
      statValue: "0.4ms",
      statLabel: "Tensor Latency",
    },
  },
  {
    id: "cyber-synthwave",
    name: "Synthwave Sunset Void",
    family: "future_tech",
    category: "Technology",
    description: "Retro-futuristic 80s synthwave dark aesthetic with hot magenta lasers and twilight orange accents.",
    bestFor: ["Gaming Tech", "Graphics Pipelines", "Interactive Media"],
    palette: {
      primary: "#FDF2F8",
      secondary: "#F472B6",
      accent: "#F43F5E",
      background: "#110E1B",
      text: "#FDF2F8",
      cardBg: "#1E1730",
      border: "#3B265E",
      isDark: true,
    },
    fontMood: "technical",
    layoutStyle: "cyber-tech",
    layoutFamily: "cyber",
    slideComposition: "deck-columns",
    shapeLanguage: "chamfered-hud",
    spacingSystem: "compact-dense",
    titlePosition: "top-left",
    cardStyle: "elevated-dark-glow",
    visualStyle: "glow",
    previewSnippet: {
      title: "Synthwave Cyber Engine",
      subtitle: "Magenta laser highlights across dark synth aesthetic",
      tag: "SYNTH ENGINE",
      statValue: "144 FPS",
      statLabel: "Render Rate",
    },
  },
  {
    id: "aurora-violet",
    name: "Northern Lights Aurora",
    family: "aurora_gradient",
    category: "Creative",
    description: "Soft cosmic atmospheric glow with deep violet backdrop and luminous emerald accents.",
    bestFor: ["AI Breakthroughs", "Vision Keynotes", "Product Teasers"],
    palette: {
      primary: "#F8FAFC",
      secondary: "#CBD5E1",
      accent: "#A855F7",
      background: "#0F0B1E",
      text: "#F8FAFC",
      cardBg: "#1C1438",
      border: "#3B2B6E",
      isDark: true,
    },
    fontMood: "clean_sans",
    layoutStyle: "aurora-gradient",
    layoutFamily: "gradient-mesh",
    slideComposition: "hero-focused",
    shapeLanguage: "rounded-xl",
    spacingSystem: "airy-generous",
    titlePosition: "top-left",
    cardStyle: "frosted-glass",
    visualStyle: "glassmorphic",
    isFeatured: true,
    previewSnippet: {
      title: "Atmospheric Cosmic Fluidity",
      subtitle: "Soft translucent gradients inspired by the Northern Lights",
      tag: "AURORA VIOLET",
      statValue: "\u221e",
      statLabel: "Horizon",
    },
  },
  {
    id: "aurora-teal",
    name: "Arctic Frost Glass",
    family: "glass_aurora",
    category: "Creative",
    description: "Crisp icy teal and azure gradients on clean frosted glass cards with high translucency.",
    bestFor: ["Clean Tech", "Biotech Research", "Environmental Seminars"],
    palette: {
      primary: "#0F172A",
      secondary: "#334155",
      accent: "#0D9488",
      background: "#F0FDFA",
      text: "#0F172A",
      cardBg: "#FFFFFF",
      border: "#CCFBF1",
      isDark: false,
    },
    fontMood: "clean_sans",
    layoutStyle: "aurora-gradient",
    layoutFamily: "gradient-mesh",
    slideComposition: "hero-focused",
    shapeLanguage: "rounded-xl",
    spacingSystem: "airy-generous",
    titlePosition: "top-left",
    cardStyle: "frosted-glass",
    visualStyle: "glassmorphic",
    previewSnippet: {
      title: "Arctic Frost Translucency",
      subtitle: "Frosted glass elevations with cool mint gradients",
      tag: "ARCTIC GLASS",
      statValue: "0.18",
      statLabel: "Carbon Index",
    },
  },
  {
    id: "bold-magazine-vogue",
    name: "Vogue Editorial Magazine",
    family: "bold_magazine",
    category: "Creative",
    description: "High-fashion serif editorial with bold column balance, refined drop caps, and timeless aesthetic discipline.",
    bestFor: ["Design Portfolio", "Humanities Research", "Creative Direction"],
    palette: {
      primary: "#18181B",
      secondary: "#71717A",
      accent: "#E11D48",
      background: "#FAFAF9",
      text: "#18181B",
      cardBg: "#FFFFFF",
      border: "#E4E4E7",
      isDark: false,
    },
    fontMood: "editorial",
    layoutStyle: "bold-magazine",
    layoutFamily: "editorial",
    slideComposition: "editorial-columns",
    shapeLanguage: "sharp-corners",
    spacingSystem: "airy-generous",
    titlePosition: "centered",
    cardStyle: "outline-only",
    visualStyle: "editorial",
    isFeatured: true,
    previewSnippet: {
      title: "High-Fashion Typographic Spread",
      subtitle: "Timeless editorial columns with crimson accent taglines",
      tag: "PARIS EDITORIAL",
      statValue: "N\u00b0 07",
      statLabel: "Edition",
    },
  },
  {
    id: "editorial-the-atlantic",
    name: "The Atlantic Longform",
    family: "bold_magazine",
    category: "Creative",
    description: "Deep journalistic editorial with classic serif headlines and generous reading rhythm.",
    bestFor: ["Sociology Research", "Public Policy", "Deep Dive Essays"],
    palette: {
      primary: "#111827",
      secondary: "#4B5563",
      accent: "#B91C1C",
      background: "#FDFBF7",
      text: "#111827",
      cardBg: "#FFFFFF",
      border: "#E5E7EB",
      isDark: false,
    },
    fontMood: "editorial",
    layoutStyle: "bold-magazine",
    layoutFamily: "editorial",
    slideComposition: "editorial-columns",
    shapeLanguage: "sharp-corners",
    spacingSystem: "airy-generous",
    titlePosition: "top-left",
    cardStyle: "outline-only",
    visualStyle: "editorial",
    previewSnippet: {
      title: "Journalistic Longform",
      subtitle: "Rich serif narrative designed for thoughtful discourse",
      tag: "LONGFORM ESSAY",
      statValue: "14 min",
      statLabel: "Read Time",
    },
  },
  {
    id: "corporate-executive",
    name: "McKinsey Executive Navy",
    family: "corporate_premium",
    category: "Professional",
    description: "Wall Street and management consulting standard: authoritative deep navy, crisp slate hierarchy, and strategic pillars.",
    bestFor: ["Board Meetings", "Strategy Proposals", "Investor Pitch Decks"],
    palette: {
      primary: "#0F172A",
      secondary: "#475569",
      accent: "#0284C7",
      background: "#FFFFFF",
      text: "#0F172A",
      cardBg: "#F8FAFC",
      border: "#E2E8F0",
      isDark: false,
    },
    fontMood: "professional",
    layoutStyle: "corporate-premium",
    layoutFamily: "corporate",
    slideComposition: "deck-columns",
    shapeLanguage: "rounded-sm",
    spacingSystem: "balanced",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    isFeatured: true,
    previewSnippet: {
      title: "Executive Strategic Briefing",
      subtitle: "Authoritative navy with structured 3-pillar consulting cards",
      tag: "MANAGEMENT SPEC",
      statValue: "+42%",
      statLabel: "EBITDA Growth",
    },
  },
  {
    id: "corporate-davos",
    name: "Davos Forum Steel",
    family: "corporate_premium",
    category: "Professional",
    description: "Sleek cool slate gray with international blue accents designed for global leadership conferences.",
    bestFor: ["Keynote Addresses", "Global Policy", "Executive Leadership"],
    palette: {
      primary: "#1E293B",
      secondary: "#64748B",
      accent: "#3B82F6",
      background: "#F1F5F9",
      text: "#0F172A",
      cardBg: "#FFFFFF",
      border: "#CBD5E1",
      isDark: false,
    },
    fontMood: "professional",
    layoutStyle: "corporate-premium",
    layoutFamily: "corporate",
    slideComposition: "deck-columns",
    shapeLanguage: "rounded-sm",
    spacingSystem: "balanced",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    previewSnippet: {
      title: "Global Leadership Brief",
      subtitle: "Crisp steel gray with international blue governance accents",
      tag: "DAVOS STEEL",
      statValue: "$12.4B",
      statLabel: "Market Cap",
    },
  },
  {
    id: "startup-electric",
    name: "Y-Combinator Pitch Deck",
    family: "startup_product",
    category: "Modern",
    description: "High-velocity venture pitch deck with electric indigo focus, rapid traction numbers, and product storytelling.",
    bestFor: ["Demo Day", "Seed Round Fundraising", "Product Teardowns"],
    palette: {
      primary: "#0F172A",
      secondary: "#64748B",
      accent: "#4F46E5",
      background: "#FFFFFF",
      text: "#0F172A",
      cardBg: "#EEF2FF",
      border: "#C7D2FE",
      isDark: false,
    },
    fontMood: "clean_sans",
    layoutStyle: "split-hero",
    layoutFamily: "split-screen",
    slideComposition: "split-50-50",
    shapeLanguage: "rounded-xl",
    spacingSystem: "balanced",
    titlePosition: "split-left-hero",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    isFeatured: true,
    previewSnippet: {
      title: "Venture Scale Traction",
      subtitle: "Bold product storytelling with left brand anchor panel",
      tag: "SERIES-A READY",
      statValue: "10x MoM",
      statLabel: "Growth Velocity",
    },
  },
  {
    id: "startup-cobalt",
    name: "Series-A Cobalt",
    family: "startup_product",
    category: "Modern",
    description: "Deep cobalt and white high-impact deck engineered to convince institutional venture capitalists.",
    bestFor: ["Institutional Funding", "B2B SaaS Growth", "Investor Updates"],
    palette: {
      primary: "#0B1536",
      secondary: "#475569",
      accent: "#2563EB",
      background: "#F8FAFC",
      text: "#0B1536",
      cardBg: "#FFFFFF",
      border: "#DBEAFE",
      isDark: false,
    },
    fontMood: "clean_sans",
    layoutStyle: "split-hero",
    layoutFamily: "split-screen",
    slideComposition: "split-50-50",
    shapeLanguage: "rounded-xl",
    spacingSystem: "balanced",
    titlePosition: "split-left-hero",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    previewSnippet: {
      title: "Cobalt Venture Metrics",
      subtitle: "Unshakable unit economics and gross margin proof",
      tag: "VENTURE READY",
      statValue: "$4.2M",
      statLabel: "ARR Run Rate",
    },
  },
  {
    id: "academic-clean",
    name: "Oxford Crimson Thesis",
    family: "academic_research",
    category: "Academic",
    description: "Rigorous academic thesis standard: elegant serif typography, crimson institution crest, and formal equation styling.",
    bestFor: ["PhD Viva Voce", "Master Thesis Defense", "Peer-Reviewed Conferences"],
    palette: {
      primary: "#1E1E24",
      secondary: "#595959",
      accent: "#991B1B",
      background: "#FDFBF7",
      text: "#1E1E24",
      cardBg: "#FFFFFF",
      border: "#E7E5E4",
      isDark: false,
    },
    fontMood: "editorial",
    layoutStyle: "academic-research",
    layoutFamily: "editorial",
    slideComposition: "editorial-columns",
    shapeLanguage: "rounded-sm",
    spacingSystem: "airy-generous",
    titlePosition: "centered",
    cardStyle: "outline-only",
    visualStyle: "editorial",
    isFeatured: true,
    previewSnippet: {
      title: "Formal Thesis Defense",
      subtitle: "Crimson crest with peer-reviewed citation hierarchy",
      tag: "OXFORD THESIS",
      statValue: "p < 0.001",
      statLabel: "Significance",
    },
  },
  {
    id: "academic-mit",
    name: "MIT Computational Charcoal",
    family: "academic_research",
    category: "Academic",
    description: "Clean modern academic aesthetic with charcoal slate tones and technical theorem containers.",
    bestFor: ["Computer Science Defense", "Algorithm Proofs", "Engineering Colloquium"],
    palette: {
      primary: "#0F172A",
      secondary: "#334155",
      accent: "#0369A1",
      background: "#F8FAFC",
      text: "#0F172A",
      cardBg: "#FFFFFF",
      border: "#E2E8F0",
      isDark: false,
    },
    fontMood: "technical",
    layoutStyle: "academic-research",
    layoutFamily: "editorial",
    slideComposition: "editorial-columns",
    shapeLanguage: "sharp-corners",
    spacingSystem: "balanced",
    titlePosition: "top-left",
    cardStyle: "outline-only",
    visualStyle: "editorial",
    previewSnippet: {
      title: "Computational Proof",
      subtitle: "Charcoal slate precision with algorithm breakdown tables",
      tag: "MIT SPEC",
      statValue: "O(log n)",
      statLabel: "Complexity",
    },
  },
  {
    id: "engineering-blueprint-cad",
    name: "Technical CAD Blueprint",
    family: "engineering_blueprint",
    category: "Technology",
    description: "Detailed engineering drafting board with CAD coordinate grid, monospace pinouts, and schematic architecture boxes.",
    bestFor: ["Hardware Engineering", "Robotics BOM", "VLSI / Circuit Demonstrations"],
    palette: {
      primary: "#E0F2FE",
      secondary: "#7DD3FC",
      accent: "#38BDF8",
      background: "#0C1D38",
      text: "#F0F9FF",
      cardBg: "#081426",
      border: "#1E3A8A",
      isDark: true,
    },
    fontMood: "technical",
    layoutStyle: "blueprint",
    layoutFamily: "blueprint",
    slideComposition: "schematic-grid",
    shapeLanguage: "sharp-corners",
    spacingSystem: "compact-dense",
    titlePosition: "top-left",
    cardStyle: "outline-only",
    visualStyle: "schematic",
    isFeatured: true,
    previewSnippet: {
      title: "CAD Schematic Architecture",
      subtitle: "Coordinate grid with technical hardware pinouts",
      tag: "CAD REV 1.4",
      statValue: "100%",
      statLabel: "BOM Spec",
    },
  },
  {
    id: "blueprint-cyan",
    name: "Schematic Cyan Vector",
    family: "engineering_blueprint",
    category: "Technology",
    description: "Precision cyan line work on deep marine navy canvas for embedded systems and aerospace hardware.",
    bestFor: ["Aerospace Defense", "Embedded Systems", "Hardware Architecture"],
    palette: {
      primary: "#ECFEFF",
      secondary: "#A5F3FC",
      accent: "#06B6D4",
      background: "#081320",
      text: "#ECFEFF",
      cardBg: "#0D2136",
      border: "#164E63",
      isDark: true,
    },
    fontMood: "technical",
    layoutStyle: "blueprint",
    layoutFamily: "blueprint",
    slideComposition: "schematic-grid",
    shapeLanguage: "sharp-corners",
    spacingSystem: "compact-dense",
    titlePosition: "top-left",
    cardStyle: "outline-only",
    visualStyle: "schematic",
    previewSnippet: {
      title: "Embedded Vector Circuit",
      subtitle: "Precision line work for mission-critical systems",
      tag: "AEROSPACE CAD",
      statValue: "0.01mm",
      statLabel: "Tolerance",
    },
  },
  {
    id: "data-dashboard",
    name: "FinTech Bloomberg Terminal",
    family: "data_storytelling",
    category: "Data",
    description: "High-density statistical metrics dashboard with oversized numbers, KPI telemetry, and quantitative proof.",
    bestFor: ["Financial Analysis", "Machine Learning Metrics", "SaaS Cohort Reports"],
    palette: {
      primary: "#F8FAFC",
      secondary: "#94A3B8",
      accent: "#10B981",
      background: "#0A0D14",
      text: "#F8FAFC",
      cardBg: "#111726",
      border: "#1E293B",
      isDark: true,
    },
    fontMood: "technical",
    layoutStyle: "data-dashboard",
    layoutFamily: "dashboard",
    slideComposition: "kpi-first",
    shapeLanguage: "rounded-xl",
    spacingSystem: "compact-dense",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    isFeatured: true,
    previewSnippet: {
      title: "Empirical Benchmark Dashboard",
      subtitle: "Dominant 32pt+ numerical KPI counters with delta badges",
      tag: "QUANT DASHBOARD",
      statValue: "99.4%",
      statLabel: "F1 Accuracy",
    },
  },
  {
    id: "data-amber",
    name: "Trading Desk Amber",
    family: "data_storytelling",
    category: "Data",
    description: "Classic quantitative trading amber telemetry on obsidian canvas with statistical charts.",
    bestFor: ["Algorithmic Trading", "Risk Management", "Statistical Physics"],
    palette: {
      primary: "#FEF3C7",
      secondary: "#D97706",
      accent: "#F59E0B",
      background: "#0D0B05",
      text: "#FEF3C7",
      cardBg: "#1C1708",
      border: "#451A03",
      isDark: true,
    },
    fontMood: "technical",
    layoutStyle: "data-dashboard",
    layoutFamily: "dashboard",
    slideComposition: "kpi-first",
    shapeLanguage: "rounded-xl",
    spacingSystem: "compact-dense",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    previewSnippet: {
      title: "Algorithmic Risk Telemetry",
      subtitle: "Amber phosphor counters with empirical verification",
      tag: "AMBER TERMINAL",
      statValue: "3.8 Sharpe",
      statLabel: "Alpha Ratio",
    },
  },
  {
    id: "timeline-roadmap",
    name: "Chrono Roadmap Horizon",
    family: "timeline_story",
    category: "Professional",
    description: "Horizontal progressive roadmap with linked milestone nodes, phase flags, and delivery stages.",
    bestFor: ["Product Roadmaps", "Project Milestones", "Sprint Execution"],
    palette: {
      primary: "#0F172A",
      secondary: "#64748B",
      accent: "#3B82F6",
      background: "#F8FAFC",
      text: "#0F172A",
      cardBg: "#FFFFFF",
      border: "#E2E8F0",
      isDark: false,
    },
    fontMood: "clean_sans",
    layoutStyle: "corporate-premium",
    layoutFamily: "timeline",
    slideComposition: "linear-flow",
    shapeLanguage: "rounded-xl",
    spacingSystem: "balanced",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    isFeatured: true,
    previewSnippet: {
      title: "Milestone Delivery Path",
      subtitle: "Chronological progressive roadmap connecting all phases",
      tag: "ROADMAP 2026",
      statValue: "Phase 03",
      statLabel: "Current Sprint",
    },
  },
  {
    id: "timeline-milestones",
    name: "Milestones Gold Horizon",
    family: "timeline_story",
    category: "Professional",
    description: "Warm bronze and gold milestone progression for enterprise delivery and multi-year roadmaps.",
    bestFor: ["Enterprise Strategy", "Government Contracts", "Multi-Year Roadmaps"],
    palette: {
      primary: "#1C1917",
      secondary: "#78716C",
      accent: "#B45309",
      background: "#FFFBEB",
      text: "#1C1917",
      cardBg: "#FFFFFF",
      border: "#FDE68A",
      isDark: false,
    },
    fontMood: "clean_sans",
    layoutStyle: "corporate-premium",
    layoutFamily: "timeline",
    slideComposition: "linear-flow",
    shapeLanguage: "rounded-xl",
    spacingSystem: "balanced",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    previewSnippet: {
      title: "Enterprise Golden Path",
      subtitle: "Structured phased progression with formal deliverables",
      tag: "ENTERPRISE PATH",
      statValue: "100%",
      statLabel: "On-Schedule",
    },
  },
  {
    id: "minimal-monochrome",
    name: "Stark Monochrome 100%",
    family: "minimal_bw",
    category: "Minimal",
    description: "Pure black and white discipline without a drop of color. Typography alone carries the entire presentation.",
    bestFor: ["Philosophy Dissertations", "Architecture Reviews", "Keynote Manifestos"],
    palette: {
      primary: "#000000",
      secondary: "#525252",
      accent: "#000000",
      background: "#FFFFFF",
      text: "#000000",
      cardBg: "#F5F5F5",
      border: "#E5E5E5",
      isDark: false,
    },
    fontMood: "bold_display",
    layoutStyle: "apple-minimal",
    layoutFamily: "minimal",
    slideComposition: "hero-focused",
    shapeLanguage: "sharp-corners",
    spacingSystem: "airy-generous",
    titlePosition: "top-left",
    cardStyle: "minimal-flat",
    visualStyle: "clean",
    isFeatured: true,
    previewSnippet: {
      title: "Zero Color. Pure Typography.",
      subtitle: "Total black and white discipline for maximum typographic gravitas",
      tag: "100% MONO",
      statValue: "100%",
      statLabel: "Contrast",
    },
  },
  {
    id: "warm-terracotta",
    name: "Terracotta Earth Editorial",
    family: "warm_editorial",
    category: "Creative",
    description: "Earthy terracotta, warm cream canvas, and toasted caramel tones with classic serif elegance.",
    bestFor: ["Sustainability Reports", "Culinary Innovation", "Design Philosophy"],
    palette: {
      primary: "#292524",
      secondary: "#78716C",
      accent: "#C2410C",
      background: "#FAF7F2",
      text: "#292524",
      cardBg: "#FFFFFF",
      border: "#E7E5E4",
      isDark: false,
    },
    fontMood: "editorial",
    layoutStyle: "bold-magazine",
    layoutFamily: "editorial",
    slideComposition: "editorial-columns",
    shapeLanguage: "rounded-xl",
    spacingSystem: "airy-generous",
    titlePosition: "centered",
    cardStyle: "outline-only",
    visualStyle: "editorial",
    isFeatured: true,
    previewSnippet: {
      title: "Earthy Organic Editorial",
      subtitle: "Warm terracotta warmth with serif narrative balance",
      tag: "EARTH SERIF",
      statValue: "Organic",
      statLabel: "Aesthetic",
    },
  },
  {
    id: "luxury-gold",
    name: "Monaco Noir & Gold",
    family: "luxury_black",
    category: "Premium",
    description: "Super-premium black and metallic gold palette with refined tracking, hairline borders, and understated prestige.",
    bestFor: ["Private Equity", "Luxury Real Estate", "Flagship Product Keynotes"],
    palette: {
      primary: "#F5F5F7",
      secondary: "#A1A1A6",
      accent: "#D4AF37",
      background: "#0A0A0A",
      text: "#F5F5F7",
      cardBg: "#141414",
      border: "#2A2A2A",
      isDark: true,
    },
    fontMood: "editorial",
    layoutStyle: "centered-editorial",
    layoutFamily: "editorial",
    slideComposition: "editorial-columns",
    shapeLanguage: "rounded-sm",
    spacingSystem: "airy-generous",
    titlePosition: "centered",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    isFeatured: true,
    previewSnippet: {
      title: "Prestige Investment Tier",
      subtitle: "Understated Monaco gold rule with deep velvet black",
      tag: "HAUTE PRESTIGE",
      statValue: "Tier 1",
      statLabel: "Allocation",
    },
  },
  {
    id: "creative-tangerine",
    name: "Pop Studio Tangerine",
    family: "creative_portfolio",
    category: "Creative",
    description: "Vivid orange and electric violet pop colors with energetic card cards and high optimism.",
    bestFor: ["Marketing Pitches", "Brand Identity", "Student Showcases"],
    palette: {
      primary: "#18181B",
      secondary: "#52525B",
      accent: "#EA580C",
      background: "#FFF7ED",
      text: "#18181B",
      cardBg: "#FFFFFF",
      border: "#FED7AA",
      isDark: false,
    },
    fontMood: "bold_display",
    layoutStyle: "organic-flow",
    layoutFamily: "memphis",
    slideComposition: "deck-columns",
    shapeLanguage: "rounded-xl",
    spacingSystem: "balanced",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    isFeatured: true,
    previewSnippet: {
      title: "High-Optimism Creative",
      subtitle: "Electric tangerine punch with playful card elevations",
      tag: "POP TANGERINE",
      statValue: "100%",
      statLabel: "Creative",
    },
  },
  {
    id: "poster-bold",
    name: "Bauhaus Billboard Poster",
    family: "poster_style",
    category: "Creative",
    description: "Massive headline-driven poster layout taking up 60% of the slide visual weight with dramatic contrast.",
    bestFor: ["Rallying Cry Keynotes", "Mission Statements", "Design Manifestos"],
    palette: {
      primary: "#0F172A",
      secondary: "#475569",
      accent: "#DC2626",
      background: "#F8FAFC",
      text: "#0F172A",
      cardBg: "#FFFFFF",
      border: "#CBD5E1",
      isDark: false,
    },
    fontMood: "bold_display",
    layoutStyle: "poster",
    layoutFamily: "poster",
    slideComposition: "poster-headline",
    shapeLanguage: "sharp-corners",
    spacingSystem: "airy-generous",
    titlePosition: "poster-oversized",
    cardStyle: "hard-border-shadow",
    visualStyle: "brutalist",
    isFeatured: true,
    previewSnippet: {
      title: "60% Dominant Billboard Title",
      subtitle: "Oversized typography designed to command total attention",
      tag: "BILLBOARD POSTER",
      statValue: "100%",
      statLabel: "Impact",
    },
  },
  {
    id: "memphis-geometric",
    name: "Memphis 1980s Retro",
    family: "memphis_pop",
    category: "Creative",
    description: "Expressive 1980s Milan Memphis movement: dashed border circles, zig-zag accents, and pastel card offsets.",
    bestFor: ["Creative Agencies", "Music & Culture", "Festival Presentations"],
    palette: {
      primary: "#18181B",
      secondary: "#52525B",
      accent: "#8B5CF6",
      background: "#FAF5FF",
      text: "#18181B",
      cardBg: "#FFFFFF",
      border: "#E9D5FF",
      isDark: false,
    },
    fontMood: "bold_display",
    layoutStyle: "organic-flow",
    layoutFamily: "memphis",
    slideComposition: "deck-columns",
    shapeLanguage: "rounded-xl",
    spacingSystem: "balanced",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    previewSnippet: {
      title: "Milan Memphis Geometry",
      subtitle: "Dashed circles and playful pastel elevations",
      tag: "MEMPHIS 1980",
      statValue: "\u2605 POP",
      statLabel: "Vibe",
    },
  },
  {
    id: "split-brand-hero",
    name: "Duet 50/50 Brand Panel",
    family: "split_screen",
    category: "Modern",
    description: "Strict split screen: solid saturated brand panel on the left anchoring the topic, right card stack for insights.",
    bestFor: ["Brand Guidelines", "Product Comparisons", "Investor Demos"],
    palette: {
      primary: "#1E1B4B",
      secondary: "#4338CA",
      accent: "#6366F1",
      background: "#F5F3FF",
      text: "#1E1B4B",
      cardBg: "#FFFFFF",
      border: "#DDD6FE",
      isDark: false,
    },
    fontMood: "clean_sans",
    layoutStyle: "split-hero",
    layoutFamily: "split-screen",
    slideComposition: "split-50-50",
    shapeLanguage: "rounded-xl",
    spacingSystem: "balanced",
    titlePosition: "split-left-hero",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    isFeatured: true,
    previewSnippet: {
      title: "Left Saturated Brand Anchor",
      subtitle: "Strong architectural 40/60 horizontal division",
      tag: "SPLIT DUET",
      statValue: "50/50",
      statLabel: "Weight",
    },
  },
  {
    id: "card-stack-elevation",
    name: "Layered Depth Matrix",
    family: "card_stack",
    category: "Modern",
    description: "Layered depth cards with physical elevation offsets, delicate drop shadows, and numerical pill indices.",
    bestFor: ["Process Flows", "System Tiers", "Sequential Architecture"],
    palette: {
      primary: "#0F172A",
      secondary: "#64748B",
      accent: "#0EA5E9",
      background: "#F0F9FF",
      text: "#0F172A",
      cardBg: "#FFFFFF",
      border: "#BAE6FD",
      isDark: false,
    },
    fontMood: "clean_sans",
    layoutStyle: "bento-grid",
    layoutFamily: "card-stack",
    slideComposition: "deck-columns",
    shapeLanguage: "rounded-xl",
    spacingSystem: "balanced",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    isFeatured: true,
    previewSnippet: {
      title: "Physical Card Elevation",
      subtitle: "Offset layered tiers creating tangible depth",
      tag: "CARD STACK",
      statValue: "Tier 3",
      statLabel: "Elevation",
    },
  },
  {
    id: "soft-pastel-sage",
    name: "Nordic Botanical Sage",
    family: "soft_pastel",
    category: "Minimal",
    description: "Soft organic eucalyptus, soothing sage greens, and warm linen surfaces for calm, persuasive storytelling.",
    bestFor: ["Wellness Products", "Environmental Science", "Human-Centered Design"],
    palette: {
      primary: "#1C2D27",
      secondary: "#4A6B5D",
      accent: "#10B981",
      background: "#F4F7F5",
      text: "#1C2D27",
      cardBg: "#FFFFFF",
      border: "#D8E4DC",
      isDark: false,
    },
    fontMood: "clean_sans",
    layoutStyle: "apple-minimal",
    layoutFamily: "minimal",
    slideComposition: "hero-focused",
    shapeLanguage: "rounded-xl",
    spacingSystem: "airy-generous",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    previewSnippet: {
      title: "Nordic Botanical Serenity",
      subtitle: "Subdued sage green and organic linen canvas",
      tag: "BOTANICAL SAGE",
      statValue: "0 CO\u2082",
      statLabel: "Neutrality",
    },
  },
  {
    id: "google-material",
    name: "Material You Adaptive",
    family: "google_editorial",
    category: "Modern",
    description: "Google Material 3 design system with pill-shaped chips, adaptive surface elevation, and friendly modern typography.",
    bestFor: ["Android / Mobile Apps", "Product Management", "Consumer Tech"],
    palette: {
      primary: "#1F1F1F",
      secondary: "#444746",
      accent: "#0B57D0",
      background: "#F8F9FA",
      text: "#1F1F1F",
      cardBg: "#FFFFFF",
      border: "#E1E3E1",
      isDark: false,
    },
    fontMood: "clean_sans",
    layoutStyle: "bento-grid",
    layoutFamily: "bento",
    slideComposition: "modular-grid",
    shapeLanguage: "rounded-full-pills",
    spacingSystem: "balanced",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    previewSnippet: {
      title: "Material 3 Adaptive Surfaces",
      subtitle: "Pill-shaped action chips with tonal container elevations",
      tag: "MATERIAL 3",
      statValue: "Adaptive",
      statLabel: "Color System",
    },
  },
  {
    id: "retro-midcentury",
    name: "Mid-Century Modernist",
    family: "retro_modern",
    category: "Creative",
    description: "1960s Palm Springs modernist aesthetic with warm mustard yellow, avocado olive, and woodcut warmth.",
    bestFor: ["Architecture History", "Design Retrospectives", "Brand Stories"],
    palette: {
      primary: "#292524",
      secondary: "#57534E",
      accent: "#CA8A04",
      background: "#FEFCE8",
      text: "#292524",
      cardBg: "#FFFFFF",
      border: "#FEF08A",
      isDark: false,
    },
    fontMood: "bold_display",
    layoutStyle: "asymmetric-grid",
    layoutFamily: "swiss-grid",
    slideComposition: "asymmetric-split",
    shapeLanguage: "rounded-sm",
    spacingSystem: "balanced",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "retro",
    previewSnippet: {
      title: "Mid-Century Warmth",
      subtitle: "1960s mustard and olive modernist typography",
      tag: "PALM SPRINGS",
      statValue: "1965",
      statLabel: "Vintage",
    },
  },
  {
    id: "apple-midnight",
    name: "Apple Midnight Blue",
    family: "apple_minimal",
    category: "Minimal",
    description: "Deep oceanic midnight blue canvas with ultra-sharp white typography and sky-blue focus elements.",
    bestFor: ["Executive Reviews", "Cloud Architecture"],
    palette: {
      primary: "#FFFFFF",
      secondary: "#94A3B8",
      accent: "#38BDF8",
      background: "#0F172A",
      text: "#FFFFFF",
      cardBg: "#1E293B",
      border: "#334155",
      isDark: true,
    },
    fontMood: "clean_sans",
    layoutStyle: "apple-minimal",
    layoutFamily: "minimal",
    slideComposition: "hero-focused",
    shapeLanguage: "rounded-xl",
    spacingSystem: "airy-generous",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    previewSnippet: {
      title: "Midnight Ocean Minimal",
      subtitle: "Deep navy airiness with sky-blue highlights",
      tag: "MIDNIGHT PRO",
      statValue: "99.9%",
      statLabel: "Clarity",
    },
  },
  {
    id: "swiss-blue",
    name: "Zurich Cobalt Engineering",
    family: "swiss_editorial",
    category: "Modern",
    description: "Mathematical Swiss grid with authoritative cobalt blue vertical guideline and strict typography.",
    bestFor: ["Engineering Defense", "Physics Papers"],
    palette: {
      primary: "#0A0A0A",
      secondary: "#525252",
      accent: "#1D4ED8",
      background: "#FFFFFF",
      text: "#0A0A0A",
      cardBg: "#F8FAFC",
      border: "#E2E8F0",
      isDark: false,
    },
    fontMood: "bold_display",
    layoutStyle: "asymmetric-grid",
    layoutFamily: "swiss-grid",
    slideComposition: "asymmetric-split",
    shapeLanguage: "sharp-corners",
    spacingSystem: "asymmetric-gutters",
    titlePosition: "top-left",
    cardStyle: "outline-only",
    visualStyle: "editorial",
    previewSnippet: {
      title: "Cobalt Zurich Grid",
      subtitle: "Rigorous typographic layout with blue spine",
      tag: "SWISS COBALT",
      statValue: "01",
      statLabel: "Chapter",
    },
  },
  {
    id: "linear-emerald",
    name: "Linear Emerald Matrix",
    family: "linear_dark",
    category: "Technology",
    description: "Developer dark mode with glowing emerald matrix telemetry lines and elevated cards.",
    bestFor: ["Distributed Databases", "Security Ops"],
    palette: {
      primary: "#F8FAFC",
      secondary: "#94A3B8",
      accent: "#10B981",
      background: "#05120E",
      text: "#F8FAFC",
      cardBg: "#0A2019",
      border: "#134234",
      isDark: true,
    },
    fontMood: "technical",
    layoutStyle: "linear-dark",
    layoutFamily: "cyber",
    slideComposition: "deck-columns",
    shapeLanguage: "rounded-xl",
    spacingSystem: "compact-dense",
    titlePosition: "top-left",
    cardStyle: "elevated-dark-glow",
    visualStyle: "glow",
    previewSnippet: {
      title: "Matrix Protocol Core",
      subtitle: "Emerald telemetry with laser card borders",
      tag: "EMERALD TELEMETRY",
      statValue: "0.12ms",
      statLabel: "Latency",
    },
  },
  {
    id: "bento-crimson",
    name: "Bento Crimson Glass",
    family: "bento_grid",
    category: "Modern",
    description: "Warm crimson accents across clean white bento grid containers with hero statistic pill.",
    bestFor: ["Health Tech", "Biomedical Defense"],
    palette: {
      primary: "#18181B",
      secondary: "#71717A",
      accent: "#E11D48",
      background: "#FFF1F2",
      text: "#18181B",
      cardBg: "#FFFFFF",
      border: "#FFE4E6",
      isDark: false,
    },
    fontMood: "clean_sans",
    layoutStyle: "bento-grid",
    layoutFamily: "bento",
    slideComposition: "modular-grid",
    shapeLanguage: "rounded-xl",
    spacingSystem: "balanced",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    previewSnippet: {
      title: "Crimson Bento Health",
      subtitle: "High impact health metrics in modular blocks",
      tag: "CRIMSON BENTO",
      statValue: "98.7%",
      statLabel: "Precision",
    },
  },
  {
    id: "neo-brutalist-cyan",
    name: "Brutalist Electric Cyan",
    family: "neo_brutalist",
    category: "Creative",
    description: "Cyan pop brutalism with 3px solid black outlines and black drop shadows.",
    bestFor: ["Student Demos", "Creative Hackathons"],
    palette: {
      primary: "#000000",
      secondary: "#1E293B",
      accent: "#06B6D4",
      background: "#ECFEFF",
      text: "#000000",
      cardBg: "#FFFFFF",
      border: "#000000",
      isDark: false,
    },
    fontMood: "bold_display",
    layoutStyle: "neo-brutalist",
    layoutFamily: "brutalist",
    slideComposition: "deck-columns",
    shapeLanguage: "brutalist-solid",
    spacingSystem: "balanced",
    titlePosition: "top-left",
    cardStyle: "hard-border-shadow",
    visualStyle: "brutalist",
    previewSnippet: {
      title: "Cyan Shock Brutalism",
      subtitle: "Heavy 3px borders with solid black drop shadows",
      tag: "CYAN POP",
      statValue: "100%",
      statLabel: "Energy",
    },
  },
  {
    id: "cyber-matrix-green",
    name: "Matrix Terminal Green",
    family: "future_tech",
    category: "Technology",
    description: "Classic phosphor green terminal aesthetic with coordinate brackets and dark cyber void.",
    bestFor: ["Cybersecurity", "Kernel Development"],
    palette: {
      primary: "#86EFAC",
      secondary: "#4ADE80",
      accent: "#22C55E",
      background: "#020804",
      text: "#86EFAC",
      cardBg: "#05180C",
      border: "#14532D",
      isDark: true,
    },
    fontMood: "technical",
    layoutStyle: "cyber-tech",
    layoutFamily: "cyber",
    slideComposition: "deck-columns",
    shapeLanguage: "chamfered-hud",
    spacingSystem: "compact-dense",
    titlePosition: "top-left",
    cardStyle: "elevated-dark-glow",
    visualStyle: "glow",
    previewSnippet: {
      title: "Phosphor Kernel Core",
      subtitle: "Monospace terminal brackets on green matrix",
      tag: "KERNEL SPEC",
      statValue: "0x7FFF",
      statLabel: "Memory",
    },
  },
  {
    id: "aurora-amber-sunset",
    name: "Solar Flare Aurora",
    family: "aurora_gradient",
    category: "Creative",
    description: "Luminous amber and sunset orange translucent glass gradients on dark canvas.",
    bestFor: ["Design Keynotes", "Creative Direction"],
    palette: {
      primary: "#FFFBEB",
      secondary: "#FDE68A",
      accent: "#F59E0B",
      background: "#1C1103",
      text: "#FFFBEB",
      cardBg: "#2B1A04",
      border: "#78350F",
      isDark: true,
    },
    fontMood: "clean_sans",
    layoutStyle: "aurora-gradient",
    layoutFamily: "gradient-mesh",
    slideComposition: "hero-focused",
    shapeLanguage: "rounded-xl",
    spacingSystem: "airy-generous",
    titlePosition: "top-left",
    cardStyle: "frosted-glass",
    visualStyle: "glassmorphic",
    previewSnippet: {
      title: "Solar Flare Gradient",
      subtitle: "Warm glowing sunset mesh across dark cards",
      tag: "SOLAR AURORA",
      statValue: "9000K",
      statLabel: "Warmth",
    },
  },
  {
    id: "editorial-harpers",
    name: "Harper's Architectural Serif",
    family: "bold_magazine",
    category: "Creative",
    description: "Sophisticated serif typography with charcoal black headers and olive green footnote accents.",
    bestFor: ["Architecture Review", "Urban Planning"],
    palette: {
      primary: "#1C1917",
      secondary: "#57534E",
      accent: "#4D7C0F",
      background: "#FAF9F6",
      text: "#1C1917",
      cardBg: "#FFFFFF",
      border: "#E7E5E4",
      isDark: false,
    },
    fontMood: "editorial",
    layoutStyle: "bold-magazine",
    layoutFamily: "editorial",
    slideComposition: "editorial-columns",
    shapeLanguage: "sharp-corners",
    spacingSystem: "airy-generous",
    titlePosition: "centered",
    cardStyle: "outline-only",
    visualStyle: "editorial",
    previewSnippet: {
      title: "Architectural Harmony",
      subtitle: "Refined editorial serif spread with olive accents",
      tag: "HARPERS SPEC",
      statValue: "Vol. 4",
      statLabel: "Series",
    },
  },
  {
    id: "corporate-deloitte",
    name: "Strategy Green Deloitte",
    family: "corporate_premium",
    category: "Professional",
    description: "Clean consulting gray with crisp green dot accent and structured executive pillars.",
    bestFor: ["Enterprise Transformation", "Audit Findings"],
    palette: {
      primary: "#111827",
      secondary: "#4B5563",
      accent: "#16A34A",
      background: "#F9FAFB",
      text: "#111827",
      cardBg: "#FFFFFF",
      border: "#E5E7EB",
      isDark: false,
    },
    fontMood: "professional",
    layoutStyle: "corporate-premium",
    layoutFamily: "corporate",
    slideComposition: "deck-columns",
    shapeLanguage: "rounded-sm",
    spacingSystem: "balanced",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    previewSnippet: {
      title: "Enterprise Transformation",
      subtitle: "Symmetrical consulting pillars with audit metrics",
      tag: "AUDIT SPEC",
      statValue: "100%",
      statLabel: "Compliance",
    },
  },
  {
    id: "startup-tangerine-pitch",
    name: "Tangerine Venture Pitch",
    family: "startup_product",
    category: "Modern",
    description: "High-octane orange and charcoal split deck for consumer internet startups.",
    bestFor: ["Seed Pitch", "Product Hunt Demos"],
    palette: {
      primary: "#18181B",
      secondary: "#52525B",
      accent: "#F97316",
      background: "#FFF7ED",
      text: "#18181B",
      cardBg: "#FFFFFF",
      border: "#FED7AA",
      isDark: false,
    },
    fontMood: "clean_sans",
    layoutStyle: "split-hero",
    layoutFamily: "split-screen",
    slideComposition: "split-50-50",
    shapeLanguage: "rounded-xl",
    spacingSystem: "balanced",
    titlePosition: "split-left-hero",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    previewSnippet: {
      title: "Consumer Traction Velocity",
      subtitle: "High energy split brand canvas with orange punch",
      tag: "SEED PITCH",
      statValue: "50K",
      statLabel: "MAU",
    },
  },
  {
    id: "academic-cambridge",
    name: "Cambridge Navy Academic",
    family: "academic_research",
    category: "Academic",
    description: "Formal Cambridge deep navy crest with crisp ivory background and serif research layout.",
    bestFor: ["University Lectures", "Fellowship Defense"],
    palette: {
      primary: "#0A192F",
      secondary: "#334155",
      accent: "#0284C7",
      background: "#F8FAFC",
      text: "#0A192F",
      cardBg: "#FFFFFF",
      border: "#E2E8F0",
      isDark: false,
    },
    fontMood: "editorial",
    layoutStyle: "academic-research",
    layoutFamily: "editorial",
    slideComposition: "editorial-columns",
    shapeLanguage: "rounded-sm",
    spacingSystem: "airy-generous",
    titlePosition: "centered",
    cardStyle: "outline-only",
    visualStyle: "editorial",
    previewSnippet: {
      title: "Peer-Reviewed Discovery",
      subtitle: "Navy crest with formal research citation layout",
      tag: "CAMBRIDGE SPEC",
      statValue: "99.8%",
      statLabel: "Confidence",
    },
  },
  {
    id: "blueprint-slate-cad",
    name: "Schematic Charcoal CAD",
    family: "engineering_blueprint",
    category: "Technology",
    description: "Dark charcoal CAD drafting grid with white vector lines and coordinate crosshairs.",
    bestFor: ["Robotics Schematics", "System Diagrams"],
    palette: {
      primary: "#F8FAFC",
      secondary: "#94A3B8",
      accent: "#38BDF8",
      background: "#18181B",
      text: "#F8FAFC",
      cardBg: "#27272A",
      border: "#3F3F46",
      isDark: true,
    },
    fontMood: "technical",
    layoutStyle: "blueprint",
    layoutFamily: "blueprint",
    slideComposition: "schematic-grid",
    shapeLanguage: "sharp-corners",
    spacingSystem: "compact-dense",
    titlePosition: "top-left",
    cardStyle: "outline-only",
    visualStyle: "schematic",
    previewSnippet: {
      title: "Charcoal CAD Pinouts",
      subtitle: "Precision line schematics with coordinate tags",
      tag: "SCHEMATIC REV 2",
      statValue: "\u00b10.05",
      statLabel: "Tolerance",
    },
  },
  {
    id: "data-emerald-kpi",
    name: "Executive KPI Terminal",
    family: "data_storytelling",
    category: "Data",
    description: "Clean light-mode enterprise analytics dashboard with large metric numbers and benchmark rows.",
    bestFor: ["Executive Business Reviews", "SaaS Metrics"],
    palette: {
      primary: "#0F172A",
      secondary: "#475569",
      accent: "#059669",
      background: "#F0FDF4",
      text: "#0F172A",
      cardBg: "#FFFFFF",
      border: "#BBF7D0",
      isDark: false,
    },
    fontMood: "technical",
    layoutStyle: "data-dashboard",
    layoutFamily: "dashboard",
    slideComposition: "kpi-first",
    shapeLanguage: "rounded-xl",
    spacingSystem: "compact-dense",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    previewSnippet: {
      title: "Enterprise KPI Counters",
      subtitle: "Emerald performance metrics with benchmark tags",
      tag: "KPI ENGINE",
      statValue: "99.95%",
      statLabel: "SLA Compliance",
    },
  },
  {
    id: "timeline-cyan-orbit",
    name: "Sprint Cycle Orbit",
    family: "timeline_story",
    category: "Professional",
    description: "Connected cycle nodes on clean slate with cyan progress chips for agile sprints.",
    bestFor: ["Agile Sprints", "Product Releases"],
    palette: {
      primary: "#0F172A",
      secondary: "#64748B",
      accent: "#06B6D4",
      background: "#ECFEFF",
      text: "#0F172A",
      cardBg: "#FFFFFF",
      border: "#A5F3FC",
      isDark: false,
    },
    fontMood: "clean_sans",
    layoutStyle: "corporate-premium",
    layoutFamily: "timeline",
    slideComposition: "linear-flow",
    shapeLanguage: "rounded-xl",
    spacingSystem: "balanced",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    previewSnippet: {
      title: "Agile Sprint Progression",
      subtitle: "Sequential release cycles with milestone indicators",
      tag: "SPRINT HORIZON",
      statValue: "Sprint 14",
      statLabel: "Current",
    },
  },
  {
    id: "poster-cyber-black",
    name: "Obsidian Billboard Manifesto",
    family: "poster_style",
    category: "Creative",
    description: "Deep black poster canvas with giant 5xl neon green typography taking over the screen.",
    bestFor: ["Keynote Openers", "Manifesto Declarations"],
    palette: {
      primary: "#FFFFFF",
      secondary: "#A1A1AA",
      accent: "#4ADE80",
      background: "#000000",
      text: "#FFFFFF",
      cardBg: "#18181B",
      border: "#27272A",
      isDark: true,
    },
    fontMood: "bold_display",
    layoutStyle: "poster",
    layoutFamily: "poster",
    slideComposition: "poster-headline",
    shapeLanguage: "sharp-corners",
    spacingSystem: "airy-generous",
    titlePosition: "poster-oversized",
    cardStyle: "hard-border-shadow",
    visualStyle: "brutalist",
    previewSnippet: {
      title: "Dark Billboard Manifesto",
      subtitle: "Massive display type commanding total audience focus",
      tag: "DARK POSTER",
      statValue: "100%",
      statLabel: "Presence",
    },
  },
  {
    id: "memphis-vibrant-teal",
    name: "Memphis Neo-Geo",
    family: "memphis_pop",
    category: "Creative",
    description: "Expressive yellow and teal geometric blocks with retro 80s flair.",
    bestFor: ["Creative Workshops", "Design Thinking"],
    palette: {
      primary: "#1E293B",
      secondary: "#475569",
      accent: "#14B8A6",
      background: "#FEFCE8",
      text: "#1E293B",
      cardBg: "#FFFFFF",
      border: "#FEF08A",
      isDark: false,
    },
    fontMood: "bold_display",
    layoutStyle: "organic-flow",
    layoutFamily: "memphis",
    slideComposition: "deck-columns",
    shapeLanguage: "rounded-xl",
    spacingSystem: "balanced",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    previewSnippet: {
      title: "Neo-Geo Memphis",
      subtitle: "Teal and yellow geometric shapes with playful elevation",
      tag: "NEO-GEO",
      statValue: "\u2605 1980",
      statLabel: "Style",
    },
  },
  {
    id: "split-dark-graphite",
    name: "Graphite Split Horizon",
    family: "split_screen",
    category: "Technology",
    description: "High contrast dark split layout: obsidian left brand panel with glowing cyan, right card deck.",
    bestFor: ["Technical Product Launches", "SaaS Demos"],
    palette: {
      primary: "#F8FAFC",
      secondary: "#94A3B8",
      accent: "#38BDF8",
      background: "#090D16",
      text: "#F8FAFC",
      cardBg: "#111827",
      border: "#1F2937",
      isDark: true,
    },
    fontMood: "clean_sans",
    layoutStyle: "split-hero",
    layoutFamily: "split-screen",
    slideComposition: "split-50-50",
    shapeLanguage: "rounded-xl",
    spacingSystem: "balanced",
    titlePosition: "split-left-hero",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    previewSnippet: {
      title: "Graphite Split Horizon",
      subtitle: "Dark obsidian brand panel with glowing cyan specs",
      tag: "SPLIT GRAPHITE",
      statValue: "40/60",
      statLabel: "Ratio",
    },
  },
  {
    id: "card-stack-dark-matrix",
    name: "Obsidian Depth Stack",
    family: "card_stack",
    category: "Technology",
    description: "Dark mode layered card stack with violet glow borders and staggered depth elevations.",
    bestFor: ["Infrastructure Tiers", "Security Architecture"],
    palette: {
      primary: "#F8FAFC",
      secondary: "#94A3B8",
      accent: "#A855F7",
      background: "#0B0C10",
      text: "#F8FAFC",
      cardBg: "#141721",
      border: "#232838",
      isDark: true,
    },
    fontMood: "clean_sans",
    layoutStyle: "bento-grid",
    layoutFamily: "card-stack",
    slideComposition: "deck-columns",
    shapeLanguage: "rounded-xl",
    spacingSystem: "balanced",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    previewSnippet: {
      title: "Obsidian Depth Stack",
      subtitle: "Layered cards with violet glow and staggered depth",
      tag: "DEPTH STACK",
      statValue: "Level 4",
      statLabel: "Depth",
    },
  },
  {
    id: "luxury-emerald-velour",
    name: "Geneva Emerald & Platinum",
    family: "luxury_black",
    category: "Premium",
    description: "Deep emerald green and platinum metallic palette for private wealth and high-end watches.",
    bestFor: ["Family Office", "Luxury Brands"],
    palette: {
      primary: "#F0FDF4",
      secondary: "#BBF7D0",
      accent: "#34D399",
      background: "#03170E",
      text: "#F0FDF4",
      cardBg: "#08291B",
      border: "#134E37",
      isDark: true,
    },
    fontMood: "editorial",
    layoutStyle: "centered-editorial",
    layoutFamily: "editorial",
    slideComposition: "editorial-columns",
    shapeLanguage: "rounded-sm",
    spacingSystem: "airy-generous",
    titlePosition: "centered",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    previewSnippet: {
      title: "Geneva Emerald Tier",
      subtitle: "Velvet emerald with platinum metallic rules",
      tag: "GENEVA PRESTIGE",
      statValue: "AAA",
      statLabel: "Rating",
    },
  },
  {
    id: "nature-forest-moss",
    name: "Deep Forest Moss",
    family: "soft_pastel",
    category: "Minimal",
    description: "Deep forest moss with warm sand accents and organic breathing room.",
    bestFor: ["Agritech", "Conservation Biology"],
    palette: {
      primary: "#F7FEE7",
      secondary: "#D9F99D",
      accent: "#65A30D",
      background: "#14230D",
      text: "#F7FEE7",
      cardBg: "#1E3614",
      border: "#365314",
      isDark: true,
    },
    fontMood: "clean_sans",
    layoutStyle: "apple-minimal",
    layoutFamily: "minimal",
    slideComposition: "hero-focused",
    shapeLanguage: "rounded-xl",
    spacingSystem: "airy-generous",
    titlePosition: "top-left",
    cardStyle: "subtle-fill",
    visualStyle: "clean",
    previewSnippet: {
      title: "Forest Moss Organic",
      subtitle: "Deep woodland green with calm organic balance",
      tag: "FOREST MOSS",
      statValue: "100%",
      statLabel: "Bio",
    },
  },
  {
    id: "warm-tuscan-sun",
    name: "Tuscan Ochre & Olive",
    family: "warm_editorial",
    category: "Creative",
    description: "Warm Mediterranean ochre and olive serif layout with inviting cream surfaces.",
    bestFor: ["Humanities", "Cultural Studies"],
    palette: {
      primary: "#292524",
      secondary: "#78716C",
      accent: "#B45309",
      background: "#FFFBEB",
      text: "#292524",
      cardBg: "#FFFFFF",
      border: "#FDE68A",
      isDark: false,
    },
    fontMood: "editorial",
    layoutStyle: "bold-magazine",
    layoutFamily: "editorial",
    slideComposition: "editorial-columns",
    shapeLanguage: "rounded-xl",
    spacingSystem: "airy-generous",
    titlePosition: "centered",
    cardStyle: "outline-only",
    visualStyle: "editorial",
    previewSnippet: {
      title: "Tuscan Sun Editorial",
      subtitle: "Warm amber ochre with serif narrative flow",
      tag: "TUSCAN OCHRE",
      statValue: "Classic",
      statLabel: "Essence",
    },
  },
  {
    id: "minimal-press-dark",
    name: "Broadsheet Obsidian Press",
    family: "minimal_bw",
    category: "Minimal",
    description: "Pure black-and-white reversed in dark mode: pure pitch black canvas with stark white typography.",
    bestFor: ["Design Manifestos", "Code Philosophy"],
    palette: {
      primary: "#FFFFFF",
      secondary: "#A3A3A3",
      accent: "#FFFFFF",
      background: "#000000",
      text: "#FFFFFF",
      cardBg: "#171717",
      border: "#262626",
      isDark: true,
    },
    fontMood: "bold_display",
    layoutStyle: "apple-minimal",
    layoutFamily: "minimal",
    slideComposition: "hero-focused",
    shapeLanguage: "sharp-corners",
    spacingSystem: "airy-generous",
    titlePosition: "top-left",
    cardStyle: "minimal-flat",
    visualStyle: "clean",
    previewSnippet: {
      title: "Pitch Black Inversion",
      subtitle: "100% monochrome dark canvas with zero noise",
      tag: "DARK MONO",
      statValue: "0%",
      statLabel: "Color",
    },
  },
  {
    id: "gradient-mesh-velvet",
    name: "Sunset Velvet Mesh",
    family: "gradient_mesh",
    category: "Creative",
    description: "Vibrant violet and coral gradient mesh with translucent cards and fluid modern typography.",
    bestFor: ["Product Launches", "Creative Portfolios"],
    palette: {
      primary: "#FAF5FF",
      secondary: "#E9D5FF",
      accent: "#EC4899",
      background: "#2E1065",
      text: "#FAF5FF",
      cardBg: "#3B0764",
      border: "#581C87",
      isDark: true,
    },
    fontMood: "clean_sans",
    layoutStyle: "aurora-gradient",
    layoutFamily: "gradient-mesh",
    slideComposition: "hero-focused",
    shapeLanguage: "rounded-xl",
    spacingSystem: "airy-generous",
    titlePosition: "top-left",
    cardStyle: "frosted-glass",
    visualStyle: "glassmorphic",
    previewSnippet: {
      title: "Velvet Gradient Mesh",
      subtitle: "Vivid coral and violet mesh with glass cards",
      tag: "VELVET MESH",
      statValue: "Fluid",
      statLabel: "Movement",
    },
  },
  {
    id: "isometric-compute",
    name: "Isometric Compute Grid",
    family: "isometric_tech",
    category: "Technology",
    description: "Technical isometric depth grid with coordinate pins and 3D architectural structure.",
    bestFor: ["Distributed Systems", "Cloud Compute"],
    palette: {
      primary: "#F8FAFC",
      secondary: "#94A3B8",
      accent: "#6366F1",
      background: "#0B0F19",
      text: "#F8FAFC",
      cardBg: "#131C2E",
      border: "#1E2D4A",
      isDark: true,
    },
    fontMood: "technical",
    layoutStyle: "blueprint",
    layoutFamily: "blueprint",
    slideComposition: "schematic-grid",
    shapeLanguage: "sharp-corners",
    spacingSystem: "compact-dense",
    titlePosition: "top-left",
    cardStyle: "outline-only",
    visualStyle: "schematic",
    previewSnippet: {
      title: "Isometric Compute Grid",
      subtitle: "3D coordinate pins on deep navy schematic",
      tag: "ISOMETRIC 3D",
      statValue: "X-Y-Z",
      statLabel: "Coordinates",
    },
  },
  {
    id: "typography-heavy-display",
    name: "Heavy Display Black",
    family: "bold_typography",
    category: "Creative",
    description: "Oversized bold display typography designed for maximum authority and visual impact.",
    bestFor: ["Executive Declarations", "Mission Statements"],
    palette: {
      primary: "#0F172A",
      secondary: "#475569",
      accent: "#4338CA",
      background: "#EEF2FF",
      text: "#0F172A",
      cardBg: "#FFFFFF",
      border: "#C7D2FE",
      isDark: false,
    },
    fontMood: "bold_display",
    layoutStyle: "poster",
    layoutFamily: "poster",
    slideComposition: "poster-headline",
    shapeLanguage: "sharp-corners",
    spacingSystem: "airy-generous",
    titlePosition: "poster-oversized",
    cardStyle: "hard-border-shadow",
    visualStyle: "brutalist",
    previewSnippet: {
      title: "Massive Headline Display",
      subtitle: "Ultra-bold typography commanding total authority",
      tag: "HEAVY DISPLAY",
      statValue: "900",
      statLabel: "Weight",
    },
  },
  {
    id: "floating-canvas-zen",
    name: "Zen Floating Canvas",
    family: "floating_canvas",
    category: "Minimal",
    description: "Airy floating cards on quiet cream canvas with subtle borderless shadows and peaceful balance.",
    bestFor: ["Mindfulness", "Design Architecture", "Brand Philosophy"],
    palette: {
      primary: "#1C1917",
      secondary: "#78716C",
      accent: "#0D9488",
      background: "#FAFAF9",
      text: "#1C1917",
      cardBg: "#FFFFFF",
      border: "#F5F5F4",
      isDark: false,
    },
    fontMood: "clean_sans",
    layoutStyle: "apple-minimal",
    layoutFamily: "minimal",
    slideComposition: "hero-focused",
    shapeLanguage: "rounded-xl",
    spacingSystem: "airy-generous",
    titlePosition: "top-left",
    cardStyle: "minimal-flat",
    visualStyle: "clean",
    previewSnippet: {
      title: "Zen Floating Canvas",
      subtitle: "Pure balance with soft borderless elevations",
      tag: "FLOATING ZEN",
      statValue: "0 Noise",
      statLabel: "Clarity",
    },
  },
  {
    id: "vercel-mono",
    name: "Vercel Carbon Mono",
    family: "vercel_mono",
    category: "Technology",
    description: "Geist-inspired minimalist developer aesthetic: strict monochrome with razor-thin hairline borders.",
    bestFor: ["Next.js Architecture", "TypeScript Seminars", "Developer Tools"],
    palette: {
      primary: "#FFFFFF",
      secondary: "#888888",
      accent: "#FFFFFF",
      background: "#000000",
      text: "#EDEDED",
      cardBg: "#111111",
      border: "#333333",
      isDark: true,
    },
    fontMood: "technical",
    layoutStyle: "linear-dark",
    layoutFamily: "cyber",
    slideComposition: "deck-columns",
    shapeLanguage: "rounded-sm",
    spacingSystem: "compact-dense",
    titlePosition: "top-left",
    cardStyle: "outline-only",
    visualStyle: "clean",
    previewSnippet: {
      title: "Geist Edge Runtime",
      subtitle: "Monochrome developer layout with hairline borders",
      tag: "VERCEL SPEC",
      statValue: "0ms",
      statLabel: "Cold Start",
    },
  },
];
